apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f waifuland.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: waifuland-prod
  name: waifuland-prod
spec:
  ports:
    - name: "4300"
      port: 4300
      targetPort: 4000
  selector:
    io.kompose.service: waifuland-prod