version: "3.1"

services:
  waifuland_api:
    container_name: waifuland_api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - 4000:4000
