apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: waifuland-api-dev

resources:
- ../../base
- sealed-secret.yaml

namePrefix: dev-

commonLabels:
  environment: dev

replicas:
- count: 1
  name: waifuland-api

images:
- name: dyallo/waifuland_api
  newTag: dev-c8596905b2043dcb90d8b9a2807547b2b14897d3
