apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: waifuland-api-dev

resources:
  - ../../base

namePrefix: dev-

commonLabels:
  environment: dev

replicas:
  - name: waifuland-api
    count: 1

images:
  - name: dyallo/waifuland_api
    newTag: dev-placeholder