apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: waifuland-api-dev

resources:
- ../../base
- sealed-secret.yaml

namePrefix: dev-

commonLabels:
  environment: dev

replicas:
- count: 1
  name: waifuland-api

images:
- name: dyallo/waifuland_api
  newTag: dev-5c541e1904c9d756a98e62a0923e4954204a5575
