apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: waifuland-api
  name: waifuland-api
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: waifuland-api
  template:
    metadata:
      labels:
        io.kompose.service: waifuland-api
        environment: prod
    spec:
      containers:
        - image: dyallo/waifuland_api:v1.0.0
          name: waifuland-api
          ports:
            - containerPort: 4000
              protocol: TCP
          envFrom:
            - secretRef:
                name: dev-waifuland-secrets
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 512Mi
              cpu: 0.5
              ephemeral-storage: 1Gi
      restartPolicy: Always
      automountServiceAccountToken: false
      securityContext:
        allowPrivilegeEscalation: false
