apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: waifuland-api
  name: waifuland-api
spec:
  ports:
    - name: 'tcp'
      port: 4000
      targetPort: 4000
  selector:
    io.kompose.service: waifuland-api
  type: NodePort