apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: waifuland-api

resources:
- ../../base

commonLabels:
  environment: prod

replicas:
- count: 2
  name: waifuland-api

images:
- name: dyallo/waifuland_api
  newTag: v1.15.2
