name: Docker Publish

on:
  push:
    branches: ['master']
    tags:
      - 'v*'

jobs:
  gitleaks:
    uses: jd-apprentice/jd-workflows/.github/workflows/gitleaks.yml@main
    with:
      runs-on: ubuntu-latest
      name: Gitleaks
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}

  develop:
    needs: [gitleaks]
    if: github.ref_name == 'master'
    uses: jd-apprentice/jd-workflows/.github/workflows/deploy.yml@main
    with:
      environment: dev
      image_tag: dev-${{ github.sha }}
      target_branch: master
      overlay_path: kubernetes/overlays/dev
      app_name: waifuland_api
      dockerfile_path: infra/docker/Dockerfile
      commit_message: 'chore: update dev image to dev-${{ github.sha }}'
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  production:
    needs: [gitleaks]
    if: startsWith(github.ref_name, 'v')
    uses: jd-apprentice/jd-workflows/.github/workflows/deploy.yml@main
    with:
      environment: prod
      image_tag: ${{ github.ref_name }}
      target_branch: master
      overlay_path: kubernetes/overlays/prod
      app_name: waifuland_api
      dockerfile_path: infra/docker/Dockerfile
      commit_message: 'chore: update image tag to ${{ github.ref_name }}'
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
